model: "Video-LLaVA-7B-hf"
model_space: "LanguageBind"
cache_dir: ".cache/"
output_prefix: "basic"
fps: 2.0
num_frames: 16
max_new_tokens: 16
prompt_type: "basic"  # Options: basic, zero_shot, fewshot, cot (automatically uses prompts/basic.txt for UCF or prompts/svw_basic.txt for SVW)
continue_from: null          # use an int index or leave null
