model: "Qwen2.5-VL-3B-Instruct"
model_space: "Qwen"
cache_dir: ".cache/"
output_prefix: "cot"
fps: 0.5
num_frames: 16
max_new_tokens: 320
prompt_type: "cot"  # Options: basic, zero_shot, fewshot, cot (automatically uses prompts/cot.txt for UCF or prompts/svw_cot.txt for SVW)
continue_from: null          # use an int index or leave null
